### ISSUE TITLE
bug and crashes the bot, how do i fix this?

### ISSUE THREAD

**Issue by GameWax** [BiizoNinja/shrek-bot#32]
Node.js v17.4.0
> shrek-bot@1.0.0 start
> node .
bot is online
/workspace/handler/index.js:44
.commands.set(arrayOfSlashCommands);
^
TypeError: Cannot read properties of undefined (reading 'commands')
at Client.<anonymous> (/workspace/handler/index.js:44:13)
at Client.emit (node:events:532:35)
at WebSocketManager.triggerClientReady (/workspace/node_modules/discord.js/src/client/websocket/WebSocketManager.js:378:17)
at WebSocketManager.checkShardsReady (/workspace/node_modules/discord.js/src/client/websocket/WebSocketManager.js:361:10)
at WebSocketShard.<anonymous> (/workspace/node_modules/discord.js/src/client/websocket/WebSocketManager.js:183:14)
at WebSocketShard.emit (node:events:520:28)
at WebSocketShard.checkReady (/workspace/node_modules/discord.js/src/client/websocket/WebSocketShard.js:474:12)
at WebSocketShard.onPacket (/workspace/node_modules/discord.js/src/client/websocket/WebSocketShard.js:446:16)
at WebSocketShard.onMessage (/workspace/node_modules/discord.js/src/client/websocket/WebSocketShard.js:300:10)
at WebSocket.onMessage (/workspace/node_modules/ws/lib/event-target.js:132:16)
at WebSocket.emit (node:events:520:28)
at Receiver.receiverOnMessage (/workspace/node_modules/ws/lib/websocket.js:970:20)
at Receiver.emit (node:events:520:28)
at Receiver.dataMessage (/workspace/node_modules/ws/lib/receiver.js:517:14)
at Receiver.getData (/workspace/node_modules/ws/lib/receiver.js:435:17)
at Receiver.startLoop (/workspace/node_modules/ws/lib/receiver.js:143:22)

**Comment by GameWax** [comment]
fixed it, but 0 support from dev :/
